#!/usr/bin/env python3
import sys
import os

# Add the package directory to sys.path
pkg_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, pkg_dir)

from voice_feedback.voice_feedback_node import main

if __name__ == '__main__':
    main()